### ISSUE TITLE
Avira believes Focusu contains malware

### ISSUE THREAD

**Issue by Fleepy** [ceilingwaffle/Focusu#1]
![image](https://user-images.githubusercontent.com/18307183/57581429-23f41700-746c-11e9-87bd-68bb550887c6.png)

https://www.avira.com/en/support-threats-summary-product?tid=147821&threat=ADWARE&track=1
Not sure what the hell happened... But apparently "OsuStatePresenter" Is classified as malware.

**Comment by ceilingwaffle** [comment]
This is likely because OsuStatePresenter.dll uses another dll to read memory of the osu! process. I guess most antivirus apps flag this behaviour as suspicious. 

The entire project is open source if you'd prefer to inspect and build from source: https://github.com/ceilingwaffle/OsuStatePresenter/

The memory reader used was created by Piotrekol, also open source, available here: https://github.com/Piotrekol/ProcessMemoryDataFinder
